# Generated by Django 5.0.6 on 2024-06-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume_change_24h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_supply', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('fully_diluted_market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
